const en = {
  app: { name: "Eduba" },
  language: { auto: "Automatic (system setting)", en: "English", ja: "日本語", "zh-Hans": "简体中文", "zh-Hant": "繁體中文" },
  notice: { welcome: "Import a PDF to proofread OCR results." },
  notices: { languageSaveFailed: "Language settings could not be saved: {{error}}", languageLoadFailed: "Language settings could not be loaded: {{error}}", menuFailed: "Language changed, but the native menu could not update: {{error}}", saveFailed: "Save failed: {{error}}", pageLoadFailed: "Could not load page: {{error}}", pdfRenderFailed: "Could not render PDF: {{error}}", genericError: "Error: {{error}}", opened: "Opened {{name}}.", pdfLoadFailed: "Could not load PDF: {{error}}", pdfInspectFailed: "Could not inspect PDF: {{error}}", importFailed: "Import failed: {{error}}", projectOpenFailed: "Could not open project: {{error}}", navigationBusy: "Pages cannot be changed while processing.", navigationSaveFailed: "Could not save before moving: {{error}}", ocrSaveFailed: "Could not save before OCR: {{error}}", ocrFailed: "OCR failed: {{error}}", exportFailed: "Export failed: {{error}}", closeBusy: "Cannot close until import or save completes.", closeSaveFailed: "Could not save before closing: {{error}}", saved: "Saved", noPendingOcr: "There are no pages waiting for OCR.", exported: "Exported.", ocrComplete: "OCR is complete.", ocrCancelled: "OCR was cancelled. Saved results remain available." },
  appErrors: { unsupportedVersion: "Unsupported project version.", desktopOnly: "Eduba desktop features are available in the Tauri app.", missingPages: "Project has no page information.", invalidManifest: "Could not read project page information. The saved file was not changed.", processedPage: "Could not create processed page.", coordinateMismatch: "Saved OCR coordinates do not match the image resolution.", imageCreate: "Could not create image.", ocrCancelled: "OCR was cancelled.", hocrMissingPage: "hOCR has no page.", noExport: "There are no OCR results to export.", extractFailed: "Could not use extracted PDF image: {{reason}}", extractReason: "Extraction failed." },
  toolbar: { bold: "Bold", italic: "Italic", superscript: "Superscript", subscript: "Subscript", bulkReplace: "Replace all" },
  bulkReplace: { title: "Replace all", source: "Selected text", replacement: "Replace with", results: "{{count}} results", selectPage: "Select this results page", clearPage: "Clear this results page", noResults: "No matching lines", previous: "Previous results page", next: "Next results page", cancel: "Cancel", apply: "Replace {{count}} selected", applying: "Replacing…", close: "Close" },
  ui: { settings: "Settings", language: "Language", close: "Close", model: "Model (.traineddata)", selectModel: "Select model", automatic: "Automatic", singleBlock: "Single block", sparseText: "Sparse text", done: "Done", importPdf: "Import PDF", open: "Open", save: "Save", undo: "Undo", redo: "Redo", ocrCurrent: "OCR current", ocrPending: "OCR pending", cancel: "Cancel", currentPage: "Current page", allPages: "All pages", logicalPages: "Logical pages", processedImage: "Processed image", recognitionLayout: "Recognition layout", tagline: "OCR proofreading desk", page: "Page {{page}}", recognizeAgain: "Recognize again", ocrSettings: "OCR settings", sourcePage: "Source {{page}}", runOcrHint: "Run OCR for the current page.", singleFileHint: "Saved in one .eduba file.", replaceDescription: "Manual corrections on this page will be replaced by the new OCR result.", logicalPageCount_one: "{{count}} logical page", logicalPageCount_other: "{{count}} logical pages", clickLine: "Click a line to edit", newProject: "New project", projectFile: ".eduba project", whole: "Whole", left: "Left", right: "Right", leftPage: "Left page", rightPage: "Right page", openPdf: "Open PDF", noOcr: "No OCR results yet", importToStart: "Import a PDF to begin", saving: "Saving…", autosave: "Autosave", idle: "Idle", back: "Back", replaceOcr: "Replace and OCR", replaceTitle: "Replace corrections?" },
} as const;
export default en;